package com.mycompany.onepiece;

import java.sql.*;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author MEDAC
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipal.class.getName());
    private Connection conexion;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        sustituirPanel(new pnlInicio());
        this.setResizable(false);
        this.setLocationRelativeTo(null);

    }

    private void sustituirPanel(JPanel p) {
        pnlContenido.removeAll();
        pnlContenido.add(p);
        pnlContenido.revalidate();
        pnlContenido.repaint();
    }

    private void conectarBaseDatos() {
        conexion = BBDD.conectar();  // <- ESTO ES LO CORRECTO
        if (conexion != null) {
            System.out.println("Conexión establecida correctamente.");
        } else {
            System.out.println("No se pudo establecer la conexión.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelmMenuLatera = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnConector = new javax.swing.JButton();
        btnDml = new javax.swing.JButton();
        btnConsultas = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        pnlContenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        PanelmMenuLatera.setLayout(new java.awt.GridLayout(6, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/op (2).png"))); // NOI18N
        PanelmMenuLatera.add(jLabel1);

        jButton1.setBackground(new java.awt.Color(255, 153, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("INICIO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PanelmMenuLatera.add(jButton1);

        btnConector.setBackground(new java.awt.Color(0, 153, 255));
        btnConector.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConector.setForeground(new java.awt.Color(0, 0, 0));
        btnConector.setText("CONECTAR");
        btnConector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectorActionPerformed(evt);
            }
        });
        PanelmMenuLatera.add(btnConector);

        btnDml.setBackground(new java.awt.Color(153, 255, 153));
        btnDml.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDml.setForeground(new java.awt.Color(0, 0, 0));
        btnDml.setText("DML");
        btnDml.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDmlActionPerformed(evt);
            }
        });
        PanelmMenuLatera.add(btnDml);

        btnConsultas.setBackground(new java.awt.Color(153, 255, 153));
        btnConsultas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConsultas.setForeground(new java.awt.Color(0, 0, 0));
        btnConsultas.setText("CONSULTAS");
        btnConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultasActionPerformed(evt);
            }
        });
        PanelmMenuLatera.add(btnConsultas);

        btnCerrar.setBackground(new java.awt.Color(204, 0, 0));
        btnCerrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(0, 0, 0));
        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        PanelmMenuLatera.add(btnCerrar);

        jPanel1.add(PanelmMenuLatera, java.awt.BorderLayout.LINE_START);

        pnlContenido.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(pnlContenido, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectorActionPerformed
        conectarBaseDatos();
        sustituirPanel(new pnlConectar());

    }//GEN-LAST:event_btnConectorActionPerformed

    private void btnDmlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDmlActionPerformed
        sustituirPanel(new pnlDML());
    }//GEN-LAST:event_btnDmlActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        sustituirPanel(new pnlCerrar());
        BBDD.desconectar();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultasActionPerformed
        sustituirPanel(new pnlConsultas());
    }//GEN-LAST:event_btnConsultasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        sustituirPanel(new pnlInicio());
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelmMenuLatera;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnConector;
    private javax.swing.JButton btnConsultas;
    private javax.swing.JButton btnDml;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlContenido;
    // End of variables declaration//GEN-END:variables
}
