/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.onepiece;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author MEDAC
 */
public class pnlConsultas extends javax.swing.JPanel {

    /**
     * Creates new form pnlConsultas
     */
    public pnlConsultas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNormales = new javax.swing.JButton();
        btnJoin = new javax.swing.JButton();
        btnGrupBy = new javax.swing.JButton();
        btnSubconsultas = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 15, 15, 15));
        jPanel1.setLayout(new java.awt.GridLayout(2, 2, 15, 15));

        btnNormales.setText("Normales");
        btnNormales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNormalesActionPerformed(evt);
            }
        });
        jPanel1.add(btnNormales);

        btnJoin.setText("JOIN");
        btnJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinActionPerformed(evt);
            }
        });
        jPanel1.add(btnJoin);

        btnGrupBy.setText("Group By");
        btnGrupBy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrupByActionPerformed(evt);
            }
        });
        jPanel1.add(btnGrupBy);

        btnSubconsultas.setText("Subconsultas");
        btnSubconsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubconsultasActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubconsultas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Consulta que muestra todas las islas registradas en la tabla Isla
    private void btnNormalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNormalesActionPerformed
        try {
            Connection con = BBDD.getConexion();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM Isla");

            String resultado = "Consulta SELECT * FROM Isla:\n\n";

            while (rs.next()) {
                resultado += "ID Isla: " + rs.getInt("id_isla")
                        + " | Nombre: " + rs.getString("nombre")
                        + " | Región: " + rs.getString("region") + "\n";
            }

            rs.close();
            st.close();

            JOptionPane.showMessageDialog(this, resultado);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnNormalesActionPerformed

    // Consulta que une tripulaciones con su isla correspondiente usando un JOIN
    private void btnJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinActionPerformed
        String sql = "SELECT Tripulacion.nombre, Tripulacion.recompensa_total, Isla.nombre AS isla "
                + "FROM Tripulacion "
                + "JOIN Isla ON Tripulacion.id_isla = Isla.id_isla";

        try {
            Connection con = BBDD.getConexion();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            String resultado = "Consulta JOIN Tripulacion + Isla:\n\n";

            while (rs.next()) {
                resultado += "Tripulación: " + rs.getString("nombre")
                        + " | Recompensa: " + rs.getInt("recompensa_total")
                        + " | Isla: " + rs.getString("isla") + "\n";
            }

            rs.close();
            st.close();

            JOptionPane.showMessageDialog(this, resultado);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnJoinActionPerformed

    // Consulta que agrupa las islas por región y cuenta cuántas hay en cada una
    private void btnGrupByActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrupByActionPerformed
        String sql = "SELECT region, COUNT(*) AS total_islas "
                + "FROM Isla "
                + "GROUP BY region";

        try {
            Connection con = BBDD.getConexion();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            String resultado = "Consulta GROUP BY región:\n\n";

            while (rs.next()) {
                resultado += "Región: " + rs.getString("region")
                        + " | Total islas: " + rs.getInt("total_islas") + "\n";
            }

            rs.close();
            st.close();

            JOptionPane.showMessageDialog(this, resultado);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnGrupByActionPerformed

    // Consulta que obtiene la tripulación con la recompensa más alta usando una subconsulta
    private void btnSubconsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubconsultasActionPerformed
        String sql = "SELECT nombre, recompensa_total "
                + "FROM Tripulacion "
                + "WHERE recompensa_total = (SELECT MAX(recompensa_total) FROM Tripulacion)";

        try {
            Connection con = BBDD.getConexion();
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);

            String resultado = "Subconsulta: Tripulación con mayor recompensa:\n\n";

            while (rs.next()) {
                resultado += "Nombre: " + rs.getString("nombre")
                        + " | Recompensa: " + rs.getInt("recompensa_total") + "\n";
            }

            rs.close();
            st.close();

            JOptionPane.showMessageDialog(this, resultado);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSubconsultasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGrupBy;
    private javax.swing.JButton btnJoin;
    private javax.swing.JButton btnNormales;
    private javax.swing.JButton btnSubconsultas;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
